DROP TABLE TRAVEL_AGENCY.TOUR;
DROP TABLE TRAVEL_AGENCY.COUNTRY;
DROP TABLE TRAVEL_AGENCY.HOTEL;
DROP TABLE TRAVEL_AGENCY.REVIEW;
DROP TABLE TRAVEL_AGENCY.TOUR_M2M_COUNTRY;
DROP TABLE TRAVEL_AGENCY.TOUR_M2M_USER;
DROP TABLE TRAVEL_AGENCY.TOUR_TYPE;
DROP TABLE TRAVEL_AGENCY."user";